### ISSUE TITLE
Add modified timestamp in reconciled LIDO-XML

### ISSUE THREAD

**Issue by klindt** [alexander-winkler/LIDOrefine#5]
Please insert timestamp in reconciled LIDO record:

<lido:recordInfoSet type="http://terminology.lido-schema.org/lido00470"> 
    <lido:recordMetadataDate type="http://terminology.lido-schema.org/lido00473"> 
        2017-10-25T23:00:42Z
    </lido:recordInfoLink>
</lido:recordInfoSet>

**Comment by alexander-winkler** [comment]
Ich habe es jetzt mal im [addDate](/alexander-winkler/LIDOrefine/tree/addDate) probiert ... die Zuordnung zu `<recordinfoSet>` ist etwas problematisch, weil es mehrere geben kann und unklar ist, wo das Datum hin soll ...
